; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html
;
; Локальный COM-порт: создайте platformio_local.ini (см. README) или
;   pio run -t upload --upload-port COMx

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
lib_deps =
    bogde/HX711@^0.7.5
    robtillaart/INA226@^0.6.6
